<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activation key' => 'Clé d\'activation',
    'Active' => 'Actif',
    'Banned' => 'Banni',
    'Credentials' => 'Identifiants',
    'E-mail' => 'E-mail',
    'If the user has superuser rights (ie: inconditional access to the admin interface).' => 'Si l\'utilisateur a des droits de super-utilisateur (comme un accès inconditionnel à l\'interface administrateur).',
    'Incorrect password (minimal length 4 symbols).' => 'Mot de passe incorrect (longueur minimale 4 symboles).',
    'Incorrect username (length between 3 and 20 characters).' => 'Nom d\'utilisateur incorrect (longueur entre 3 et 20 caractères).',
    'Last visit' => 'Dernière visite',
    'No roles defined.' => 'Aucun rôle définit.',
    'Not active' => 'Inactif',
    'Only letters, capitals and numbers are permitted, no spaces and special characters (A-z0-9).' => 'Seulement les lettres, majuscules et chiffres sont permis, pas de caractères spéciaux(A-z0-9).',
    'Password' => 'Mot de passe',
    'Profile' => 'Profil',
    'Retype Password' => 'Retaper mot de passe',
    'Retype Password is incorrect.' => 'Retaper mot de passe est incorrect.',
    'Roles' => 'Rôles',
    'Status' => 'État',
    'Superuser' => 'Super-utilisateur',
    'The activation key is used for account activation and password recovery.' => 'La clé d\'activation est utilisée pour l\\activation de comptes et la récupération de mots de passe.',
    'The roles associated to this user. A role is a set of permissions and is created using the access control module.' => 'Les rôles associés à cet utilisateur. Un rôle est un groupe de permission créé à l\'aide du module de contrôle d\'accès.',
    'The status of this account.' => 'L\'état de ce compte.',
    'The user name. Between 3 and 20 characters long.' => 'Le nom de l\'utilisateur. D\'une longueur entre 3 et 20 caractères.',
    'This user email address already exists.' => 'L\'adresse e-mail de cet utilisateur existe déjà.',
    'This user name already exists.' => 'Le nom de cet utilisateur existe déjà.',
    'Username' => 'Nom d\'utilisateur',
    'Verification Code' => 'Code de vérification',
    '{n, plural, =1{User}other{Users}}' => '{n, plural, =1{Utilisateur}other{Utilisateurs}}',
];
