<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  '{n, plural, =1{Assigment}other{Assignments}}' => '{n, plural, =1{Assigation}other{Assignations}}',
  'The authorization item does not exist.' => 'L\'item d\'autorisation n\'existe pas.',
  'The name of the authorization item to assign to the user.' => 'Le nom de l\'item d\'autorisation à assigner à l\'utilisateur.',
  'The user to which this item is assigned.' => 'L\'utilisateur auquel cet item est assigné.',
  'This assigment already exists.' => 'Cet assigment existe déja',
  'User ID' => 'ID d\'Utilisateur',
);
