<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Association' => 'Association',
    'Children' => 'Enfants',
    'Permission' => 'Permission',
    'Rule name' => 'Nom de la règle',
    'A name that uniquely identifies the authorization item.' => 'Un nom unique identifiant cet item d\'autorisation.',
    'A short description of the function of the authorization item.' => 'Une description courte de la fonction de cet item d\'autorisation.',
    'An authorization item with this name already exists.' => 'Un item d\'autorisation avec ce nom existe déjà.',
    'Description' => 'Description',
    'Name' => 'Nom',
    'Role' => 'Rôle',
    'Rules' => 'Règles',
];
