<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
  'A link to the administration page of the model.' => 'Un lien vers la page d\'administration du modèle',
  'Action' => 'Action',
  '{n, plural, =1{ActiveRecord Log Entry}other{ActiveRecord Log Entries}}' => '{n, plural, =1{Entrée du journal des ActiveRecord}other{Entrées du journal des ActiveRecord}}',
  'Administration Url' => 'Url d\'administration',
  'Attribute' => 'Attribut',
  'Date/Time' => 'Date/Heure',
  'Model' => 'Modèle',
  'Model ID' => 'ID du Modèle',
  'Model Table' => 'Table du Modèle',
  'Model Title' => 'Titre du Modèle',
  'New Attribute Value' => 'Nouvelle valeur de l\'attribut',
  'Previous Attribute Value' => 'Valeur précédente de l\'attribut',
  'The ID of the model.' => 'L\'ID du modèle',
  'The ID of the user that manipulated the record.' => 'L\'ID de l\'utilisateur ayant manipulé cette entrée.',
  'The action on the model.' => 'L\'action sur le modèle.',
  'The database table of the model.' => 'La table de base de données du modèle.',
  'The date/time of the operation.' => 'La date/heure de l\'opération.',
  'The model that was manipulated.' => 'Le modèle ayant été manipulé',
  'The modified attribute.' => 'L\'attribut modifié',
  'The name of the user that manipulated the record.' => 'Le nom de l\'utilisateur ayant manipulé cette entrée.',
  'The new value of the attribute.' => 'La nouvelle valeur de l\'attribut',
  'The previous value of the attribute.' => 'La valeure précédente de l\'attribut.',
  'The title of the model at the time is was modified.' => 'Le titre du modèle au moment de sa modification',
  'User' => 'Utilisateur',
  'User ID' => 'ID d\'utilisateur',
];
