<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin Menu' => 'Menu Admin',
    'Administration' => 'Administration',
    'All' => 'Tous',
    'Arguments' => 'Arguments',
    'CSS Class' => 'Classe CSS',
    'CSS class for the menu item.' => 'Classe CSS pour l\'item de menu.',
    'Display Rule' => 'Règle d\'Affichage',
    'Display Side' => 'Côté d\'affichage',
    'Displayed' => 'Affiché',
    'Enabled' => 'Activé',
    'Footer Menu' => 'Menu Pied',
    'Fragment' => 'Fragment',
    'Header Menu' => 'Menu Tête',
    'If this menu item is active or not. A disabled item is displayed but cannot be clicked.' => 'Si cet item est activé ou non. Un item désactivé est affiché mais ne peut être cliqué.',
    'If this menu item should be displayed or hidden.' => 'Si cet item de menu doit être affiché ou caché.',
    'Main Menu' => 'Menu Principal',
    'Model "{id}" with class "{class}" does not exist!' => 'Le modèle "{id}" avec la classe "{class}" n\'existe pas!',
    'Model ID' => 'ID du Modèle',
    'Model class' => 'Classe du Modèle',
    'Model class "{class}" does not exist!' => 'La classe de modèle "{class}" n\'existe pas!',
    'Name' => 'Nom',
    'PHP code that will be eval\'d to determine if the menu item is visible.' => 'Code PHP qui sera évalué pour déterminer si l\'item de menu est visible.',
    'Parameters' => 'Paramètres',
    'Parent Menu' => 'Menu Parent',
    'Position' => 'Position',
    'Route' => 'Route',
    'Side mismatch. Side must be compatible with parent\'s.' => 'Côté invalide. Le côté doit être compatible avec celui du parent.',
    'Side on which this menu item will be displayed.' => 'Côté du site dans lequel cet item de menu sera affiché.',
    'Site' => 'Site',
    'Target' => 'Cible',
    'The display name of this item.' => 'Le nom affiché de cet item.',
    'The position of this item relative to its siblings. Click on "Set on last position" to get the value of the last position + 1 and put this item at the end of the list.' => 'La position de cet item est relative à ses semblables. Cliquez sur "Régler à la dernière position" pour régler la position à la dernière valeur + 1.',
    'The request parameters that complete the route all separated by a slash (eg. /id/8/name/foo).' => 'Les paramètres de requête complétant la route tous séparés par un slash (ex: /id/8/name/foo).',
    'The route (url) this menu item links to. For internal links, route is a controller/action pair. For external links, the link is in full with the protocol specified (eg: http://).' => 'La route (url) à laquelle cet item de menu refère. Pour les liens internes, ;a route est une paire controlleur/action. Pour les liens externes, le lien est complet avec le protocole spécifié (ex: http://).',
    'The target attribute of the menu item\'s link.' => 'L\'attribut "target" du lien de l\'item de menu.',
    'This menu item\'s parent. On the site, this item will be displayed as a child of its parent.' => 'Le parent de cet item de menu. Sur le site, cet item sera affiché comme enfant de son parent.',
    'URL arguments without the question mark.' => 'Arguments du URL sans le point d\'interrogation.',
    'URL fragment without the pound.' => 'Fragment du URL sans le dièse.',
    '{n, plural, =1{Menu item}other{Menu items}}' => '{n, plural, =1{Élément de menu}other{Éléments de menu}}',
];
