<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'A detailed description of the steps taken to trigger the error.' => 'Une description détaillée des étapes à suivre afin de reproduire l\'erreur.',
  'Browser' => 'Navigateur',
  'Date/Time' => 'Date/Heure',
  'Description' => 'Description',
  'Error code' => 'Code d\'erreur',
  'Error message' => 'Message d\'erreur',
  'Method' => 'Méthode',
  'Screen height' => 'Hauteur de l\'écran',
  'Screen width' => 'Largeur de l\'écran',
  'Send me a copy' => 'Envoyez-moi une copie',
  'The HTTP method of the request that triggered the error.' => 'La méthode HTTP de la requête ayant causé l\'erreur.',
  'The URL of the referring page.' => 'L\'URL de la page référente.',
  'The URL that triggered the error.' => 'L\'URL ayant causé l\'erreur.',
  'The browser in use when the error occured.' => 'La navigaeur utilisé lorsque l\'erreur est survenue.',
  'The user ID logged id when the error occured. Set to 0 if it was a guest.' => 'L\'ID utilisateur enregistré lorsque l\'erreur est survenue. Régler à 0 pour les invités.',
  'URL Referrer' => 'URL référent',
  'User ID' => 'ID d\'Utilisateur',
);
