<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Expression must return array.' => '',
    'Host' => '',
    'The pattern for the host.' => '',
    'A comma separated list of the language codes this rule applies to. Leave empty if it applies to all languages.' => 'Une liste de chaque langue séparées par des virgules auquelles cette règle s\'applique. Laissez vide si elle s\'applique à toutes les langues.',
    'Default parameters' => 'Paramètres par défaut',
    'Enabled' => 'Activé',
    'Enables this rule.' => 'Active cette règle.',
    'Encode parameters' => 'Encoder les paramètres',
    'Evaluation of {attr} fails.' => 'L\'évaluation de {attr} a échoué.',
    'Evaluation of {attr} throws {exception} with message {message}.' => 'L\'évaluation de {attr} a échoué avec le message {message}.',
    'If URL parameters should be encoded.' => 'Si les paramètres d\'URL devraient être encodés.',
    'If the rule is for both creation and parsing of URLs or both.' => 'Si la règle est pour la création d\'URLs, l\'analyse d\'URLs ou les deux',
    'If this rule has been automatically generated.' => 'Si cette règle a été générée automatiquement.',
    'Languages' => 'Langues',
    'Mode' => 'Mode',
    'Pattern' => 'Patron',
    'Position' => 'Position',
    'Route' => 'Route',
    'System generated' => 'Générée par le système',
    'The HTTP verb (e.g. GET, POST, DELETE) that this rule should match. If this rule can match multiple verbs, please separate them with commas. If this property is not set, the rule can match any verb. Note that this property is only used when parsing a request. It is ignored for URL creation.' => 'Le verbe HTTP (ex: GET, POST, DELETE) auquel cette règle s\'applique. Si cette règle doit s\'appliquer à plusieurs verbers, les séparer avec des virgules. Si cet attribut n\'est pas renseigné, la règle s\'appliquera à tous les verbes. Noter que cette propriété est utilisée seulement lors de l\'analyse d\'une requête. Elle est ignorée pour la création d\'URLs.',
    'The URL suffix used for this rule. For example, ".html" can be used so that the URL looks like pointing to a static HTML page. Leave empty to use the default suffix.' => 'Le suffixe d\'URLs utilisé pour cette règle. Par exemple ".html" peut être renseigné pour faire en sorte que le URL donne l\'impression de pointer vers une page HTML statique. Laisser vide pour utiliser le suffixe par défaut.',
    'The controller/action pair.' => 'La paire controlleur/action.',
    'The default GET parameters (name=>value) that this rule provides. When this rule is used to parse the incoming request, the values declared in this property will be injected into $_GET.' => 'Les paramètres GET par défaut (nom=>valeur) fournis par cette règle. Lorsque cette règle est utilisée pour analyser une requête entrante, les valeurs que cet attribut déclare seront injectées dans $_GET.',
    'The precedence of this rule.' => 'La précédence de cette règle par rapport aux autres.',
    'The regular expression used to parse and match URLs.' => 'L\'expression régulière utilisée pour analyser et générer les URLs.',
    'URL suffix' => 'Suffixe URL',
    'Verb' => 'Verbe',
    '{n, plural, =1{URL rewriting rule}other{URL rewriting rules}}' => '{n, plural, =1{Règle de réécriture d\'URLs}other{Règles de réécriture d\'URLs}}',
];
