<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
    'Destination directory ({dir}) is read-only' => 'Le répertoire de destination ({dir}) est en lecture-seule',
    '{file} is too large, maximum file size is {sizeLimit}.' => '{file} est trop volumineux, la taille maximale est {sizeLimit}.',
    '{file} is too small, minimum file size is {minSizeLimit}.' => '{file} est trop petit, la taille minimale est {minSizeLimit}.',
    'File missing' => 'Fichier manquant'
);
