<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Adresse',
    'Admin Preferences' => 'Préferences d\'administration',
    'Administration Panel' => 'Panneau d\'administration',
    'Administration panel display mode' => 'Mode d\'affichage du panneau d\'administration',
    'Administration panel display parameters' => 'Paramètres d\'affichage du panneau d\'administration',
    'Annoucement' => 'Annonce',
    'Application Configuration' => 'Configuration de l\'Application',
    'Brand / Company / Corporate' => 'Marque / Entreprise / Raison sociale',
    'Closure' => 'Fermeture',
    'Contact' => 'Contact',
    'Database' => 'Base de données',
    'Default social metas' => 'Metas sociales par défaut',
    'Domains' => 'Domaines',
    'Errors' => 'Erreurs',
    'External tools' => 'Outils externes',
    'Framework' => 'Framework',
    'Graphic elements' => 'Éléments graphiques',
    'Languages' => 'Langues',
    'Maintenance' => 'Maintenance',
    'Owner' => 'Propriétaire',
    'Parameters were saved sucessfully.' => 'Les paramètres ont été sauvegardés avec succès.',
    'Run' => 'Exécuter',
    'Run all tasks' => 'Exécuter toutes les tâches',
    'Tasks' => 'Tâches',
    'Titles' => 'Titres',
    'Users' => 'Utilisateurs',
    'Warnings' => 'Avertissements',
    'Web application' => 'Application Web',
];
