<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'Controls' => 'Contrôles',
  'Name' => 'Nom',
  'Opens the link in the same frame as it was clicked (default).' => 'Ouvrir le lien au même endroit où il a été cliqué (par défaut).',
  'Opens the link in a new window or tab.' =>  'Ouvrir le lien dans une nouvelle fenêtre ou un nouvel onglet.',
  'Opens the link in the parent frame.' => 'Ouvrir le lien dans la fenêtre on l\'onglet parent.',
  'Opens the link in the full body of the window.' => 'Ouvrir le lien dans une nouvelle fenêtre au dessus du reste.',
  'Parent' => 'Parent',
  'Position' => 'Position',
  'Presentation' => 'Présentation',
  'URL' => 'URL',
);
