<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Associate an existing object' => 'Associer un objet existant',
    'Choose an existing object' => 'Choisissez un objet existant',
    'Choose an object type' => 'Choisissez un type d\'objet',
    'Create and associate' => 'Créer et associer',
    'Create and associate a new object' => 'Créer et associer un nouvel objet',
    'New object creation is not available in this window.' => 'L\'association par la création d\'un nouvel objet n\'est pas disponible dans cette fenêtre.',
    'No available objects' => 'Aucun objet trouvé',
    'Thumbnail' => 'Vignette',
    'Title' => 'Titre',
    'View in other page' => 'Voir dans une autre page',
    'object found' => 'objet trouvé',
    'objects found' => 'objets trouvés',
];
