<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'An uninformed modification to the values displayed below could break the site. Please inform your webmaster before you make any modification to those values.' => 'Une erreur lors de la modification des valeurs affichées ci-dessous pourrait entraîner un bris du site. Veuillez informer votre webmaster avant de modifier ces valeurs.',
    'Cancel changes and go back to the manage page' => 'Annuler les changements et retourner à la page de gestion',
    'Create' => 'Créer',
    'Create a new identical record' => 'Créer une entrée identique',
    'Create a new {model}' => 'Créer un nouvel objet {model}',
    'Go back to previous form' => 'Retour au formulaire précédent',
    'Manage' => 'Gestion',
    'Record {id} was sucessfully saved' => 'L\'entrée {id} a été sauvegardée avec succès',
    'Return' => 'Retour',
    'Return to the index page' => 'Retour à la page index',
    'Save record to the database' => 'Sauvegarder cette entrée dans la base de donnée',
    'Save record to the database and continue editing' => 'Sauvegarder cette entrée dans la base de données et continuer l\'édition',
    'Save record to the database and create a copy' => 'Sauvegarder cette entrée dans la base de données et en créer une copie',
    'Save record to the database and return to previous page' => 'Sauvegarder cette entrée dans la base de données et retourner à la page précédente',
    'Save record to the database and view in site' => 'Sauvegarder cette entrée dans la base de données et voir dans le site',
    'The item was successfully deleted.' => 'L\'objet a été supprimé avec succès.',
    'The model managed by this resource does not support creation.' => 'Le modèle géré par cette resource ne supporte pas la création',
    'There was an error while deleting the item.' => 'Une erreur est survenue lors de la supression de l\'objet.',
    'Update' => 'Modifier',
    'Update, search and delete {model}' => 'Modifier, rechercher et supprimer des {model}',
    'View in site' => 'Voir dans le site',
    '{title} was sucessfully saved' => '{title} a été sauvegardée avec succès',
];
