<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'The request could not be understood by the server due to malformed syntax. Please do not repeat the request without modifications.' => '',
    'The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.' => '',
    'The request could not be understood by the server due to malformed syntax. Please do not repeat the request without modifications.' => 'La demande n\'a pas pu être interprétée par le serveur à cause d\'une mauvaise syntaxe. Merci de ne pas répeter la requête sans modifications.',
    'The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.' => 'L\'URL demandé n\'existe pas sur ce serveur. Si vous avez saisi l\'URL manuellement, vérifiez la, et réessayez.',
    'An internal error occurred while the Web server was processing your request.' => 'Une erreur interne est apparue lorsque le serveur web traitait votre requête.',
    'Bad request' => 'Demande Incorrecte',
    'Error' => 'Erreur',
    'Forbidden' => 'Accès interdit',
    'If the error was not expected, you have the possibility to {report} it.' => ' Si l\'erreur n\'était pas prévue, vous avez la possibilité de la {report}.',
    'Internal server error' => 'Erreur interne du serveur',
    'Method not allowed' => 'Méthode non supportée',
    'Not found' => 'Page non trouvée',
    'Not implemented' => 'Non-implémenté',
    'Our system is currently under maintenance. Please come back later.' => 'Notre système est momentanément indisponible. Merci de réessayer plus tard.',
    'Service unavailable' => 'Service non disponible',
    'The above error occurred when the Web server was processing your request' => 'L\'erreur ci-dessus est apparue pendant que le serveur Web traitait votre requête.',
    'The resource requested exists but it does no support the method provided.' => 'La ressource demandée existe mais elle ne supporte pas la méthode fournie.',
    'The system did not recognize the request method, or it lacks the ability to fulfill the request' => 'Le système n\'a pas reconnu la méthode de la requête ou n\'est pas capable d\'y répondre.',
    'Unauthorized' => 'Non autorisé',
    'You do not have the proper credential to access this page.' => 'Vous n\'avez pas les autorisations nécessaires pour accéder à cette page.',
    'report' => 'rapporter',
];
