<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Home' => 'Accueil',
    'Download' => 'Télécharger',
    'Empty' => 'Vide',
    'Next' => 'Suivant',
    'Open' => 'Ouvrir',
    'Previous' => 'Précédent',
    'Record was sucessfully saved' => 'L\'entrée a été sauvegardée avec succès',
    'Unknown' => 'Inconnu',
    'View in site' => 'Voir dans le site',
    'Add' => 'Ajouter',
    'Back' => 'Retour',
    'Cancel' => 'Annuler',
    'Close' => 'Fermer',
    'Controls' => 'Contrôles',
    'Create' => 'Créer',
    'Delete' => 'Supprimer',
    'Disabled' => 'Désactivé',
    'Display' => 'Afficher',
    'Down' => 'Descendre',
    'Edit' => 'Modifier',
    'First' => 'Premier',
    'Last' => 'Dernier',
    'Manage' => 'Gérer',
    'Modify' => 'Modifier',
    'No' => 'Non',
    'None' => 'Aucun',
    'Save' => 'Sauvegarder',
    'Select an item' => 'Choisissez un item',
    'Show' => 'Montrer',
    'Up' => 'Monter',
    'Update' => 'Modifier',
    'View' => 'Voir',
    'Warning' => 'Avertissement',
    'Yes' => 'Oui',
];
