<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
    'Click on the image to refresh the code.' => 'Cliquez sur l\'image pour rafraîchir le code.',
    'Letters are not case-sensitive.' => 'Les lettres ne sont pas sensibles à la casse.',
    'Please enter the letters as they are shown in the image above.' => 'Veuillez inscrire les lettres tel qu\'affiché dans l\'image.',
);
