<?php 
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Administration panel display mode' => 'Mode d\'affichage du panneau d\'administration',
    'advanced' => 'avancé',
    'standard' => 'standard',
    'The administration interface can be displayed in two modes: <ul><li>the <b>standard mode</b>, which displays functions most useful for editing the site, </li><li> the <b>advanced mode</b>, which displays all menus, including those that require an advanced knowledge of the system.</li></ul>' =>
        'L\'interface d\'administration peut être affichée selon deux modes: <ul><li> le <b>mode standard</b>, qui affiche les fonctions les plus utiles pour éditer le site, </li><li> le <b>mode avancé</b>, qui affiche tous les menus, incluant ceux qui demandent une connaissance approfondie du système.</li></ul>',
];
