<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Catchphrase' => 'Accroche',
    '<em>Bing AppID</em>' => '<em>AppID Bing</em>',
    '<em>Facebook Admin ID</em>' => '<em>Admin ID Facebook</em>',
    '<em>Google Analytics</em> key' => 'Clé <em>Google Analytics</em>',
    'A short description of the site\'s content.' => 'Une courte description du contenu du site.',
    'Alternate domains' => 'Domaines alternatifs',
    'Annoucement' => 'Annonce',
    'Apple touch icon' => 'Icône Apple touch',
    'Application e-mail' => 'Courriel de l\'application',
    'Application name' => 'Nom de l\'application',
    'Available languages' => 'Langues disponibles',
    'Background image used if no other has been specified.' => 'Image d\'arrière plan utilisée si aucune autre n\'a été renseignée.',
    'Brand/company/corporate logo' => 'Logo de marque/entreprise/raison sociale',
    'Brand/company/corporate name' => 'Nom de marque/entreprise/raison sociale',
    'City' => 'Ville',
    'Copyrights &copy;' => 'Droits d\'auteur &copy;',
    'Country' => 'Pays',
    'Default background image' => 'Image de fond par défaut',
    'Default e-mail address used by the application.' => 'Courriel par défaut utilisé par l\'application',
    'Default thumbnail' => 'Vignette par défaut',
    'Default thumbnail to display when the website is shared on social networks.' => 'Vignette par défaut à afficher lorsque le site est partagé sur les réseaux sociaux.',
    'Disable user accounts' => 'Désactiver les comptes utlisateurs',
    'Disable user accounts. Logged in users are automatically logged out. This should be accompanied by an announcement message.' => 'Désactiver les comptes utlisateurs. Les utilisateurs enregistrés sont désenregristrés automatiquement. Cette mesure devrait être accompagnée d\'une annonce.',
    'Disable user registration' => 'Désactiver l\'inscription d\'utlisateurs',
    'E-mail' => 'Courriel',
    'E-mail 2' => 'Courriel 2',
    'Emergency maintenance mode' => 'Mode d\'entretien d\'urgence',
    'Enable AJAX navigation' => 'Activer la navigation AJAX',
    'Fax' => 'Fax',
    'Icon used to add the web application on Apple mobile home screen.' => 'Icône utilisée pour ajouter l\'application l\'écran d\'acceuil d\'un mobile Apple.',
    'If the client environement is in this list, <a href="{href}" target="_blank">a warning page</a> is displayed.' => 'Si l\'environemment du client est dans cette liste, <a href="{href}" target="_blank">une page d\'avertissement</a> est affiché.',
    'Incompatible browsers' => 'Navigateurs incompatibles',
    'Keywords separated by commas that best describe the site\'s content.' => 'Mots-Clés séparés par des virgules décrivant le contenu du site.',
    'Languages available within the web application.' => 'Les langues disponibles dans l\'application web.',
    'Logo' => 'Logo',
    'Logo reduced' => 'Logo réduit',
    'Main domain' => 'Domaine principal',
    'Meta description' => 'Meta description',
    'Meta keywords' => 'Meta mots-clés',
    'Owner last name' => 'Nom de famille du propriétaire',
    'Owner name' => 'Prénom du propriétaire',
    'Postal code' => 'Code postal',
    'Puts the site in emergency maintenance mode which prevents access to anyone excepts administrators.' => 'Met le site en mode entretien d\'urgence ce qui bloque son accès à tous sauf les administrateurs',
    'Read-only mode' => 'Mode lecture seule',
    'Require javascript' => 'Javascript requis',
    'Session timeout' => 'Expiration de la session',
    'Street' => 'Rue',
    'Telephone' => 'Téléphone',
    'Telephone 2' => 'Téléphone 2',
    'Text to display in a banner everywhere on the web application.' => 'Texte à afficher dans une bannière partout dans l\'application web.',
    'The application name is used in the title for all pages of the web application.' => 'Le nom de l\'application est utilisé dans le titre de toutes les pages de l\'application web.',
    'The domains that should redirect to the main domain.' => 'Les domaines qui devraient être redirigés vers le domaine principal.',
    'The key provided by <em>Facebook</em> to synchronise the web application with their services.' => 'La clé fournie par <em>Facebook</em> pour synchroniser l\'application web avec leurs services.',
    'The key provided by <em>Google Analytics</em> to synchronise the web application with their audience analysis services.' => 'La clé fournie par <em>Google Analytics</em> pour synchroniser l\'application web avec leurs services d\'analyse d\'audience.',
    'The key provided by <em>Microsoft Bing</em> to synchronise the web application with their services.' => 'La clé fournie par <em>Microsoft Bing</em> pour synchroniser l\'application web avec leurs services.',
    'The logo displayed in the navigation bar with small screen sizes.' => 'Le logo affiché dans la barre de navigation avec de petites tailles d\'écrans.',
    'The logo displayed in the navigation bar.' => 'Le logo affiché dans la barre de navigation.',
    'The main domain used by the web application.' => 'Le domaine principal utilisé par l\'application web.',
    'The number of seconds without activity after which the user session expires.' => 'Le nombre de secondes d\'inactivité permises avant l\'expiration de la session de l\'utilisateur.',
    'The web application slogan. Displayed along with the name in the title of the front page.' => 'Le slogan de l\'application web affiché avec le nom dans le titre de la page principale.',
    'Web browsers use favicons in the address bar, title bar, bookmarks, tabs and other shortcuts.' => 'Les navigateurs web utilisent les favicons dans la barre d\'adresse, la barre de titre, les favoris, les onglets et autres raccourcis.',
    'When checked access to the registration form is disabled.' => 'Lorsque coché, empêche l\'accès au formulaire d\'inscription.',
    'When checked, enable the AJAX navigation if this is available.' => 'Lorsque coché, active la navigation AJAX si celle-ci est disponible.',
    'When checked, if javascript is not enabled in the client browser, a warning message is displayed.' => 'Lorsque coché, si javascript n\'est pas activé dans le navigateur du client, un message d\'avertissement est affiché.',
    'When checked, set the web application in read-only mode, which displays a warning message and prevents writes to the database.' => 'Lorsque coché, l\'application web passe en mode lecture seule. Dès lors, il n\'est plus possible d\'écrire sur la base de donnée et un message d\'avertissement est affiché.',
    'app.favicon' => 'app.favicon',
];
