<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'A recovery e-mail was sent to your account\'s address.' => 'Un e-mail de récupération a été envoyé à l\'adresse de votre compte.',
  'Account deletion is permanent, are you sure you want to proceed?' => 'La supression de comptes est définitive, êtes-vous sûr de vouloir continuer?',
  'Changes have been saved.' => 'Les changements ont été sauvegardés.',
  'Account deletion confirmation' => 'Confirmation de la supression du profil',
  'Delete account' => 'Supprimer mon compte',
  'Invalid recovery link.' => 'Lien de récupération invalide.',
  'Login' => 'Connexion',
  'Password recovery' => 'Récupération de mot de passe',
  'Password reset' => 'Réinitialisation du mot de passe',
  'Please enter your user name or email address.' => 'Veuillez entrer votre nom d\'utilisateur ou votre adresse e-mail.',
  'Profile' => 'Profil',
  'Recovery of a non-active or banned account is forbidden.' => 'La récupération d\'un compte banni ou désactivé est interdite.',
  'Send' => 'Envoyer',
  'Sending the message failed, please try again later.' => 'L\'envoi du message a échoué, veuillez réessayer plus tard.',
  'This account cannot be recovered, please contact your administrator.' => 'Ce compte ne peut pas être récupéré. Veuillez contacter votre administrateur.',
  'This profile does not contain visible fields.' => 'Ce profil ne contient aucun champ visible.',
  'Warning: account deletion is permanent!' => 'Avertissement: la supression de comptes est définitive!',
  'Your account could not be deleted, please try again later or contact an administrator.' => ' Votre compte n\'a pas pu être supprimé. Veuillez réessayer plus tard ou contacter un administrateur.',
  'Your account has been deleted.' => 'Votre compte a été supprimé.',
  'Your password was reset. Please login to start using the service again.' => 'Votre de mot de passe a été réinitialisé, veuillez vous enregistrer pour vous servir du service à nouveau.',
  '{siteName} - Password recovery' => '{siteName} - Recupération de mot de passe',
  '{username}\'s Profile' => 'Profil de {username}',
);
