<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Register' => 'S\'inscrire',
    'Incorrect activation URL.' => 'URL d\'activation incorrect.',
    'Registration' => 'Inscription',
    'Sending the message failed, please try again later.' => 'L\'envoi du message a échoué, veuillez réessayer plus tard.',
    'Thank you for registering. You are now logged in.' => 'Merci de vous êtres inscrit. Vous êtes maintenant connectés.',
    'Thank you for your registration. An activation e-mail was sent to the address provided.' => 'Merci de vous être inscrit. Un e-mail d\'activation a été envoyé à l\'adresse fournie.',
    'Thank you for your registration. Please contact an administrator to activate your account.' => 'Merci de vous être inscrit. Veuillez contacter un administrateur pour activer votre compte.',
    'This account is already active.' => 'Ce compte est déjà actif.',
    'This account is not active.' => 'Ce compte est désactivé.',
    'Your account is now active. Please log in to start using the service.' => 'Votre compte est maintenant actif. Veuillez vous enregistrer pour commencer à utiliser le service.',
    '{siteName} - account activation' => '{siteName} - activation de compte',
];
