<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'A configuration array' => 'Un array de configuration',
  'A description that will be displayed with this item.' => 'Une description qui sera affichée avec cet item.',
  'Configuration' => 'Configuration',
  'Configuration is invalid.' => 'Configuration n\'est pas valide.',
  'Configuration must return an array.' => 'Configuration doit retourner un array.',
  'Configuration throws exception: {e}.' => 'Configuration lance l\'exception: {e}.',
  '{n, plural, =1{Custom field}other{Custom fields}}' => '{n, plural, =1{Champ personalisé}other{Champs personalisés}}',
  'Default' => 'Valeur par défaut',
  'Description' => 'Description',
  'Display in forms' => 'Afficher dans les formulaires',
  'Form group' => 'Groupe de formulaire',
  'If deletion or renaming should be forbidden once the field has been created.' => 'Si la supression ou la modification du nom doivent être interdits une fois le champ créé.',
  'If the field should have an input in forms.' => 'Si ce champ doit faire partie des formulaires.',
  'If the field should have associated translations.' => 'Si ce champ doit avoir des traductions associées.',
  'If this field can be left blank.' => 'Si ce champ peut être laissé vide.',
  'Minimum size' => 'Taille minimale',
  'Name' => 'Nom',
  'Protected' => 'Protégé',
  'Required' => 'Obligatoire',
    'Since this field is stored in a special way, its type cannot be changed.' => 'Comme ce champ est stocké de manière spéciale, son type ne peut pas être changé.',
  'Size' => 'Taille',
  'Syntax error!' => 'Erreur de syntaxe!',
  'The data type of this field.' => 'Le type de donnée du champ.',
  'The database name of this item.' => 'Le nom de cet item en base de donnée.',
  'The display title of this item.' => 'Le titre affiché de cet item.',
  'The field\'s default value.' => 'La valeur par défaut du champ.',
  'The form group this field will be part of.' => 'Le groupe de formulaire duquel ce champ fera partie.',
  'The name of class inheriting from CValidator can be given to conduct custom validation on the field.' => 'Le nom d\'une classe héritant de CValidator peut être renseigné afin de personaliser la validation du champ.',
  'The position of this field in the form.' => 'La position de champ dans le formulaire.',
  'The validator class {class} cannot be found.' => 'La class de validation {class} n\'est pas trouvable.',
  'Title' => 'Titre',
  'Translatable' => 'Traduisible',
  'Type' => 'Type',
  'Validator' => 'Validateur',
  '{class} must inherit from CValidator.' => '{class} doit hériter de CValidator.',
);
