<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: FileField.php 2192 2016-05-03 19:48:22Z Mercier $
 */
return array (
    'An integer specifying the limit of files that can be uploaded.' => 'Un entier spéficiant le nombre maximal de fichiers pouvant être téléchargés.',
    'An integer specifying the maximum size in bytes of each file. Set to 0 for no limit.' => 'Un entier spécifiant la taille maximale de chaque fichier. Régler à 0 pour ignorer ce paramètre.',
    'An integer specifying the minimum size in bytes of each file. Set to 0 for no limit.' => 'Un entier spécifiant la taille minimale de chaque fichier. Régler à 0 pour ignorer ce paramètre.'
);
