<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Level' => 'Niveau',
    'Parent' => 'Parent',
    'Parent form group' => 'Group de formulaire parent',
    'The level at which the form group is to be displayed. This field is used by themes to position form elements.' => 
        'Le niveau auquel le group de formulaire doit être affiché. Ce champ est utilisé par les thèmes pour positionner les éléments de formulaire.',
    'Associated table' => 'Table associée',
    'Collapsed' => 'Fermé',
    'If the form group should be collapsed by default.' => 'Si le groupe de formulaire devrait être fermé par défaut.',
    'Name' => 'Nom',
    'Position' => 'Position',
    'The name of the form group.' => 'Le nom du groupe de formulaire',
    '{n, plural, =1{Form group}other{Form groups}}' => '{n, plural, =1{Groupe de formulaire}other{Groupes de formulaire}}',
];
