<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array (
  'A php array preceeded by a return statement that will be passed to tinyMCE for configuration or a direct modification of the default configuration stored in $config.' => 'Un array php précédé d"un énoncé "return" qui sera passé à tinyMCE comme configuration ou la modification directe de la configuration par défaut stockée dans $config.',
  'Configuration has a syntax error.' => '@@Configuration a une erreur de syntaxe.@@',
  'Configuration throws exception: {e}.' => '@@Configuration lance l\'exception {e}.@@',
);
