<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Model must implement ViewableInterface.' => 'Le modèle doit implémenter l\'interface ViewableInterface.',
    'Query condition "{condition}" is not valid.' => 'Condition de requête "{condition}" n\'est pas valide.',
    'associatableModelClasses has syntax error.' => 'associatableModelClasses a une erreur de syntaxe.',
    'associatableModelClasses must be an array.' => 'associatableModelClasses doit être un array',
    'associatableModelClasses throws exception: {e}.' => 'associatableModelClasses lance l\'exception: {e}.',
    '{attribute} does not exist in {class}.' => '{attribute} n\'existe pas dans {class}.',
    '{class} does not exist or has not been included.' => '{class} n\'existe pas ou n\'a pas été incluse.',
];
