<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: VarcharField.php 2192 2016-05-03 19:48:22Z Mercier $
 */
return array (
    'The maximum size of this field.' => 'La taille maximale de ce champ.',
    'The minimum size of this field. Set to 0 if none.' => 'La taille minimale de ce champ. Régler à 0 lorsque ceci n\'est pas requis.'
);
