<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'One or more files are being uploaded, if you leave now the upload will be cancelled.' => 'Un fichier est en cours de téléchargement, quitter la page annulera le transfert.',
    'The text between double braces allows to insert dynamic content, such as a list of objects. It is advised not to edit those items. ex : "{{$listOfObjects}}".' => '@@Le texte entre double accolades permet l\'insertion de contenu dynamique comme une liste de d\'objets. Il est recommande de ne pas modifier cet élément. exemple: {{$listDObjets}}@@',
    'Cancel' => 'Annuler',
    'Create a gallery' => 'Créer une gallerie',
    'Failed' => 'Échec',
    'If you copy and paste some text, it is advised to clean the format and the code by using the tools "Remove Format" (eraser) and "Clean Code" (brush) to start on a clean base.' => 'En cas de copie de texte, il est préférable de nettoyer le format et le code en utlisant les outils "Supprimer le formatage" (gomme) et "Nettoyer le code" (balayette) afin de partir sur une base propre.',
    'In case of problems please do not hesitate to contact your webmaster.' => 'En cas de problèmes n\'hésitez pas à contacter votre webmaster.',
    'Paragraph' => 'Paragraphe',
    'Subtitle {level}' => 'Sous-titre {level}',
    'The size of the text should not exceed {charCounter} characters.' => 'La taille du texte ne devrait pas dépasser {charCounter} caractères.',
    'To create a new paragraph press "Enter".' => 'Pour créer un nouveau paragraphe appuyer sur "Entrer".',
    'To create a new paragraph press "Shift + Enter".' => 'Pour créer un nouveau paragraphe appuyer sur "Maj. Flottante + Entrer".',
    'To skip a line without changing paragraph press "Enter".' => 'Pour passer à la ligne sans changer de paragraphe appuyer sur "Entrer".',
    'To skip a line without changing paragraph press "Shift + Enter".' => 'Pour passer à la ligne sans changer de paragraphe appuyer sur "Maj. Flottante + Entrer".',
    'Upload a file' => 'Télécharger un fichier',
    'Upload an image' => 'Télécharger une image',
    '{file} has invalid extension. Only {extensions} are allowed.' => '{file} a une extension interdite. Seulement {extensions} sont permis.',
    '{file} is empty, please select files again without it.' => '{file} est vide, veuillez refaire votre sélection.',
    '{file} is too large, maximum file size is {sizeLimit}.' => '{file} est trop volumineux, la taille maximale est {sizeLimit}.',
    '{file} is too small, minimum file size is {minSizeLimit}.' => '{file} est trop petit, la taille minimale est {minSizeLimit}.',
];
