<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Problem report sucessfully sent.' => 'Rapport de problème envoyé avec succès.',
    'Contact' => 'Contact',
    'Could not send report, please try again later.' => 'Le rapport n\'a pas pu être envoyé. Veuillez réessayer plus tard.',
    'Description' => 'Description',
    'ERROR: BROWSER OUT-OF-DATE' => 'ERREUR : NAVIGATEUR OBSOLÈTE',
    'Here is a list of recent browsers that work perfectly on <strong>{platform}</strong>.' => 'Voici une liste de navigateurs récents fontionnant parfaitement sur <strong>{platform}</strong>.',
    'If you have updated your browser or were taken here by mistake, click <a href="{url}">here</a> to go back to the site.' => 'Si votre navigateur a été mis à jour ou si vous croyez avoir été dirigé à cette page par erreur, cliquez <a href="{url}">ici</a> pour revenir au site.',
    'Ignore this warning' => 'Ignorer cet avertissement',
    'It is very likely that the site will malfunction. Keep going?' => 'Il est très probable que le site ne fonctionnera pas correctement. Continuer?',
    'Please select one:' => 'Veuillez en choisir un :',
    'Problem Report' => 'Rapport de Problème',
    'Problem report already sent.' => 'Rapport de problème déjà envoyé.',
    'Send problem report' => 'Envoyer rapport de problème',
    'Technical Information' => 'Information Techniques',
    'The website <strong>{app}</strong> requires a more recent browser.' => 'Le site <strong>{app}</strong> nécéssite un navigateur plus récent.',
    'YOUR BROWSER IS OUT-OF-DATE' => 'VOTRE NAVIGATEUR EST OBSOLÈTE',
    '{app} Problem Report' => 'Rapport de Problème pour {app}',
];
