<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: PhpCodeField.php 2192 2016-05-03 19:48:22Z Mercier $
 */
return array (
    'The field\'s default value. For technical reasons, it cannot be validated so be very careful of what you put here!' => 
        'La valeur par défaut du champ. Pour des raisons techniques, cette dernière ne peut être validée alors soyez très prudent!',
);
