<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Administration' => 'Administration',
    'Username or password incorrect' => 'Nom d\'utilisation ou mot de passe incorrect',
    'Edit my account' => 'Modifier mon compte',
    'I forgot my password' => 'J\'ai oublié mon mot de passe',
    'Go to admin home panel' => 'Aller au panneau d\'accueil de l\'admin',
    'Login' => 'Entrer',
    'Logout' => 'Sortir',
    'Register' => 'S\'inscrire',
    'View my account' => 'Voir mon compte',
];
