<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel' => 'Annuler',
    'Failed' => 'Échec',
    'No files found' => 'Aucun fichiers trouvés',
    'One or more files are being uploaded, if you leave now the upload will be cancelled.' => 'Un ou des fichiers sont présentement en téléchagrement, si vous quittez la page le téléchargement sera annulé.',
    'Upload a file' => 'Télécharger un fichier',
    '{file} has invalid extension. Only {extensions} are allowed.' => '{file} a une extension interdite. Seulement {extensions} sont permis.',
    '{file} is empty, please select files again without it.' => '{file} est vide, veuillez refaire votre sélection.',
    '{file} is too large, maximum file size is {sizeLimit}.' => '{file} est trop volumineux, la taille maximale est {sizeLimit}.',
    '{file} is too small, minimum file size is {minSizeLimit}.' => '{file} est trop petit, la taille minimale est {minSizeLimit}.',
];
